### ISSUE TITLE
Feature Request: Want This for Ghost

### ISSUE THREAD

**Issue by ghost** [BitChute/commentfreely#1]
Would like to be able to use this commenting system with a Ghost.org blog.

**Comment by tcreek** [comment]
Well, that is why the code is here, but incomplete and abandoned.

**Comment by rayvahey** [comment]
We​ will​ be​ moving this​ to​ gitlab and​ doing​ a​ first​ release​ in​
the​ near future

**Comment by rayvahey** [comment]
Moving to gitlab
