### ISSUE TITLE
CommentFreely as a name.

### ISSUE THREAD

**Issue by JasonCarswell** [BitChute/commentfreely#2]
"CommentFreely" is superior to "Comment Freely" as a name, for marketing and branding purposes, not to mention searches.  A more unique name would be even better.  CommFree, ChuteTheChat, or whatever.  Maybe have a democratic contest.

I tried to add a Comment Freely section to the Wikipedia article on BitChute.  It was literally guarded by a gorilla (https://en.wikipedia.org/w/index.php?title=BitChute&action=history) who claimed it was not notable, as if he/she/it/they are the arbiter of notable content.  Not worth the battle - yet.

According to the ridiculously rigged rules of Wikipedia I need more sources to cite.  A search on Google and DuckDuckGo for "Comment Freely" provides anything but content about this app.

Thus a better name is most critical, especially before it takes off as BitChuters should know.

Also, please check out SaidIt.net as an opensource civilized free speech voting forum alternative to Raddle, Reddit, and Voat.

For more information on SaidIt check out: https://SaidIt.net/s/SaidIt/wiki/ - central information hub about SaidIt, including a FAQ and links, like my encyclopedic article: https://infogalactic.com/info/SaidIt

For an example of SaidIt subs check out: https://SaidIt.net/s/DecentralizeAllThings/

Thanks for your attention,
~ Jason

P.S. Also, for muckrakes, add a download button to BitChute or get the torrenting to work!!!  Until you do I'll never be a dedicated BitChute user, just an advocate for alternatives and decentralization, including BitChute but not for BitChute.  And I really want to be.  For years now.

**Comment by tcreek** [comment]
Why would you even be on Wikipedia?

**Comment by rayvahey** [comment]
We're moving to gitlab, release there soon

**Comment by tcreek** [comment]
Any ETA or guesstimate for a project update and move to GitLab? Disqus is now heavily censoring the site.  Even worse than YouTube is.

**Comment by tcreek** [comment]
If it keeps up, people are talking about fleeing to other platforms
